---
- name: Listen for events on a webhook
  hosts: all
  ## Define our source for events
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  ## Define the conditions we are looking for
  rules:
    - name: Test Rule
      condition: event.payload is defined
      action:
        debug:
    - name: Test Rule Conditional
      condition: 
        all:
          - event.payload is defined
          - event.payload.message contains '/var/log'
      action:
        debug:
  #   - name: Say Hello
  #     condition: event.payload.message == "Ansible is super cool!
  # ## Define the action we should take should the condition be met
  #     action:
  #       run_playbook:
  #         name: say-what.yml
